### ISSUE TITLE
set On item click listener

### ISSUE THREAD

**Issue by mneckoee** [ZieIony/MaterialRecents#6]
Hi, thanks for your widget.
I set OnClickListener but doesn't work.
in RecentsList.java: 
`card.setOnClickListener(new OnClickListener() {
                @Override
                public void onClick(View v) {
                    // do something here
                    }
                }
            });`

**Comment by ghost** [comment]
whats the solution,i am also not able to set on click listener in card ,please let me know if you find anything.

**Comment by ZieIony** [comment]
It was a bug in RecentsList. I just added onItemClickListener and fixed the issue with passing touches.
