### ISSUE TITLE
Issue while compiling

### ISSUE THREAD

**Issue by meMuhammadkamal** [ZieIony/MaterialRecents#7]
Warning:Dependency com.github.ZieIony:MaterialRecents:d2aec46f48 on project app resolves to an APK archive which is not supported as a compilation dependency. File: C:\Users~.gradle\caches\modules-2\files-2.1\com.github.ZieIony\MaterialRecents\d2aec46f48\494f96d345471f38b6f3f4c1c42347a2b42f8303\MaterialRecents-d2aec46f48.apk

**Comment by ZieIony** [comment]
It's an app, not a library. If you wish, you can copy RecentsList.java to your project and use it. If you prefer a library, this widget is a part of Carbon (https://github.com/ZieIony/Carbon)
